<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/Database/Database.php';
require_once __DIR__ . '/middleware/Authentication.php';
require_once __DIR__ . '/Handlers/ErrorHAndler.php';
require_once __DIR__ . '/Exceptions/ExceptionResponse.php';
require_once __DIR__ . '/Mailer/Mail.php';
